.nh
.TH TYPISKT 1 2020\-06\-08 Linux "User Manuals"
.SH NAME
.PP
\fB\fCtypiskt\fR \- touchtype training for dirt\-hackers

.SH SYNOPSIS
.PP
.RS

.nf
typiskt [\-\-difficulty|\-d INT] [\-\-corpus|\-c WORDLIST] [\-\-time|\-t SECONDS] [\-\-width|\-w WIDTH]
typiskt \-\-list|\-l
typiskt \-\-help|\-h
typiskt \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
https://github.com/rr\-/10ff length

.SH OPTIONS
.PP
\fB\fC\-\-difficulty\fR|\fB\fC\-d\fR INT

.PP
\fB\fC\-\-corpus\fR|\fB\fC\-c\fR WORDLIST

.PP
\fB\fC\-\-time\fR|\fB\fC\-t\fR SECONDS

.PP
\fB\fC\-\-width\fR|\fB\fC\-w\fR WIDTH

.PP
\fB\fC\-\-list\fR|\fB\fC\-l\fR

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH ENVIRONMENT
.PP
\fB\fCXDG\_CONFIG\_HOME\fR

.PP
defaults to: $HOME/.config

.SH DEPENDENCIES
.PP
\fB\fCbash\fR

.PP
budRich https://github.com/budrich/typiskt
\[la]https://github.com/budrich/typiskt\[ra]

.SH SEE ALSO
.PP
https://github.com/rr\-/10ff,
