.nh
.TH TYPISKT 1 2020\-06\-08 Linux "User Manuals"
.SH NAME
.PP
\fB\fCtypiskt\fR \- SHORT DESCRIPTION

.SH SYNOPSIS
.PP
.RS

.nf
typiskt \-\-help|\-h
typiskt \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
LONG DESCRIPTION

.SH OPTIONS
.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH ENVIRONMENT
.PP
\fB\fCXDG\_CONFIG\_HOME\fR

.PP
defaults to: $HOME/.config

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCsed\fR

.PP
budRich https://github.com/budlabs
\[la]https://github.com/budlabs\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), sed(1),
